### ISSUE TITLE
Missing validation logic - command.cs

### ISSUE THREAD

**Issue by Henil23** [idkcoder93/Ground-Station-Tier#10]
As the logic which validates the input of latitude and longitude, certain test cases are failing which are meant to test for invalid inputs of Latitude and Longitude.

The range of value for latitude should be -90 to 90.
the range of value for longitude should be -180 to 180.

**Comment by idkcoder93** [comment]
I have implemented range validation for corresponding inputs (latitude and longitude). Additionally, command type is now strictly alphanumeric and doesn't accept other data types.
